version: '3.5'

networks:
  ticketnet:
    name: ticketnet

services:
  main:
    container_name: ticket_main
    stop_signal: SIGINT
    build: ./requirement/main
    volumes:
      - ticketmain:/var/it_ticket
    env_file: .env

volumes:
  ticketmain:
    name: ticketmain
    driver: local
    driver_opts:
      device: ./requirement/main/it_ticket
      o: bind
      type: none
